### ISSUE TITLE
Great demo for the WT32-SC01-PLUS

### ISSUE THREAD

**Issue by wimdm1** [SubCoderHUN/WT32-SC01-PLUS#5]
Many thanks for this demo it works great.
I had some problems with another projects and I thought that my WT32-SC01-PLUS was broken. 
But with your demo I got the confirmation that the hardware is OK.
In the other project each time I tried to use the WiFi he was starting to reboot continuously.
But with your demo I could let it run for hours and the pinging in the monitor proofed that the WiFi stayed connected and never had any reboot.
Maybe a smaller remark: some documentation about the configuration of the WiFi could help, it took me a while before I found out that after entering the SSID + PWD you need to click on the hands in the upper right corner. And that an SD card is also useful.
If you still search for some extra test for the unused GPIO pins: what about temp sensor (DS18B20) or humidity sensor (BME280)?

**Comment by SubCoderHUN** [comment]
Thank you for your feedback!
I'm glad the demo helped confirm that your hardware is functioning correctly. Regarding the issues with your other project, the WiFi rebooting problem might be due to a software or configuration issue.

Your suggestion about adding more detailed documentation on the WiFi configuration is valuable, as the step of clicking the hand icon in the upper right corner after entering the SSID and password might not be immediately obvious.

Your idea to test unused GPIO pins with a DS18B20 temperature sensor or a BME280 humidity sensor is excellent! This would be a great way to further evaluate unused GPIO pins. If you’d like, feel free to share more about your projects or challenges, and I’d be happy to assist! :)

**Comment by aramix** [comment]
> Thank you for your feedback! I'm glad the demo helped confirm that your hardware is functioning correctly. Regarding the issues with your other project, the WiFi rebooting problem might be due to a software or configuration issue.
> 
> Your suggestion about adding more detailed documentation on the WiFi configuration is valuable, as the step of clicking the hand icon in the upper right corner after entering the SSID and password might not be immediately obvious.
> 
> Your idea to test unused GPIO pins with a DS18B20 temperature sensor or a BME280 humidity sensor is excellent! This would be a great way to further evaluate unused GPIO pins. If you’d like, feel free to share more about your projects or challenges, and I’d be happy to assist! :)

Is this an AI generated response? )))

**Comment by SubCoderHUN** [comment]
Why do you think that? :P

**Comment by aramix** [comment]
It was too similar to ChatGPT responses in the wording and the way of structuring sentences :D was just curious lol
Thanks for the repo BTW! This was the only one I could follow and migrate my existing project to WT32-SC01-PLUS and LovyanGFX!

**Comment by SubCoderHUN** [comment]
Hehe😁
I'm really pleased the repository helped you with your project migration.
If there's anything else you need or if you run into any problems, just reach out. Cheers!
